import { DEFAULT_TASK_RECORD_PAGE_LAYOUT_ID } from '@/page-layout/constants/DefaultTaskRecordPageLayoutId';
import { type PageLayout } from '@/page-layout/types/PageLayout';
import {
  PageLayoutTabLayoutMode,
  PageLayoutType,
  WidgetConfigurationType,
  WidgetType,
} from '~/generated-metadata/graphql';

export const DEFAULT_TASK_RECORD_PAGE_LAYOUT: PageLayout = {
  __typename: 'PageLayout',
  id: DEFAULT_TASK_RECORD_PAGE_LAYOUT_ID,
  name: 'Default Task Layout',
  type: PageLayoutType.RECORD_PAGE,
  objectMetadataId: null,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  deletedAt: null,
  tabs: [
    {
      __typename: 'PageLayoutTab',
      applicationId: '',
      id: '20202020-ab05-4005-8005-ba5ca11a5501',
      title: 'Home',
      icon: 'IconHome',
      position: 100,
      layoutMode: PageLayoutTabLayoutMode.VERTICAL_LIST,
      pageLayoutId: DEFAULT_TASK_RECORD_PAGE_LAYOUT_ID,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deletedAt: null,
      widgets: [
        {
          __typename: 'PageLayoutWidget',
          id: '20202020-ac05-4005-8005-ba5ca11a5511',
          pageLayoutTabId: '20202020-ab05-4005-8005-ba5ca11a5501',
          title: 'Fields',
          type: WidgetType.FIELDS,
          objectMetadataId: null,
          gridPosition: {
            __typename: 'GridPosition',
            row: 0,
            column: 0,
            rowSpan: 12,
            columnSpan: 12,
          },
          configuration: {
            __typename: 'FieldsConfiguration',
            configurationType: WidgetConfigurationType.FIELDS,
            viewId: null,
          },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
        },
        {
          __typename: 'PageLayoutWidget',
          id: '20202020-ac05-4005-8005-ba5ca11a5512',
          pageLayoutTabId: '20202020-ab05-4005-8005-ba5ca11a5501',
          title: 'Note',
          type: WidgetType.FIELD_RICH_TEXT,
          objectMetadataId: null,
          gridPosition: {
            __typename: 'GridPosition',
            row: 12,
            column: 0,
            rowSpan: 6,
            columnSpan: 12,
          },
          configuration: {
            __typename: 'FieldsConfiguration',
            configurationType: WidgetConfigurationType.FIELDS,
            viewId: null,
          },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
          conditionalDisplay: {
            and: [
              {
                '===': [{ var: 'device' }, 'MOBILE'],
              },
            ],
          },
        },
      ],
    },
    {
      __typename: 'PageLayoutTab',
      applicationId: '',
      id: '20202020-ab05-4005-8005-ba5ca11a5502',
      title: 'Note',
      icon: 'IconNotes',
      position: 150,
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      pageLayoutId: DEFAULT_TASK_RECORD_PAGE_LAYOUT_ID,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deletedAt: null,
      widgets: [
        {
          __typename: 'PageLayoutWidget',
          id: '20202020-ac05-4005-8005-ba5ca11a5521',
          pageLayoutTabId: '20202020-ab05-4005-8005-ba5ca11a5502',
          title: 'Note',
          type: WidgetType.FIELD_RICH_TEXT,
          objectMetadataId: null,
          gridPosition: {
            __typename: 'GridPosition',
            row: 12,
            column: 0,
            rowSpan: 6,
            columnSpan: 12,
          },
          configuration: {
            __typename: 'FieldsConfiguration',
            configurationType: WidgetConfigurationType.FIELDS,
            viewId: null,
          },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
          conditionalDisplay: {
            and: [
              {
                '===': [{ var: 'device' }, 'DESKTOP'],
              },
            ],
          },
        },
      ],
    },
    {
      __typename: 'PageLayoutTab',
      applicationId: '',
      id: '20202020-ab05-4005-8005-ba5ca11a5503',
      title: 'Timeline',
      icon: 'IconTimelineEvent',
      position: 200,
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      pageLayoutId: DEFAULT_TASK_RECORD_PAGE_LAYOUT_ID,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deletedAt: null,
      widgets: [
        {
          __typename: 'PageLayoutWidget',
          id: '20202020-ac05-4005-8005-ba5ca11a5531',
          pageLayoutTabId: '20202020-ab05-4005-8005-ba5ca11a5503',
          title: 'Timeline',
          type: WidgetType.TIMELINE,
          objectMetadataId: null,
          gridPosition: {
            __typename: 'GridPosition',
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12,
          },
          configuration: {
            __typename: 'FieldsConfiguration',
            configurationType: WidgetConfigurationType.FIELDS,
            viewId: null,
          },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
        },
      ],
    },
    {
      __typename: 'PageLayoutTab',
      applicationId: '',
      id: '20202020-ab05-4005-8005-ba5ca11a5504',
      title: 'Files',
      icon: 'IconPaperclip',
      position: 300,
      layoutMode: PageLayoutTabLayoutMode.CANVAS,
      pageLayoutId: DEFAULT_TASK_RECORD_PAGE_LAYOUT_ID,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deletedAt: null,
      widgets: [
        {
          __typename: 'PageLayoutWidget',
          id: '20202020-ac05-4005-8005-ba5ca11a5541',
          pageLayoutTabId: '20202020-ab05-4005-8005-ba5ca11a5504',
          title: 'Files',
          type: WidgetType.FILES,
          objectMetadataId: null,
          gridPosition: {
            __typename: 'GridPosition',
            row: 0,
            column: 0,
            rowSpan: 6,
            columnSpan: 12,
          },
          configuration: {
            __typename: 'FieldsConfiguration',
            configurationType: WidgetConfigurationType.FIELDS,
            viewId: null,
          },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
        },
      ],
    },
  ],
};
